easy_admin:
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    entities:
        # List the entity class name you want to manage
        News:
            class: App\Entity\News
            form:
                fields:
                    - {property: 'description', type: 'fos_ck_editor'}
                    - {property: 'content', type: 'fos_ckeditor'}
        Tag:
            class: App\Entity\Tag